---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-interno
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-interno
  template:
    metadata:
      labels:
        app: portal-interno
    spec:
      containers:
        - name: portal-interno
          image: ghcr.io/prefeitura-rio/portal-interno:stable
          envFrom:
            - secretRef:
                name: portal-interno-secrets
      restartPolicy: Always

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portal-interno-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: portal-interno

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal-interno
  name: portal-interno
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    app: portal-interno
